#
# The other gems that this app uses
#
# To use them:
# 
#  $ gem install bundler  # incase you don't have it
# 
#  $ bundle               # makes the devmode bundle 
#                         #    and updates Gemfile.lock (dont touch)
#                         # 

source :gemcutter
source "http://rubygems.org"

group :development, :test do

  gem 'rake'             # ruby's make
  gem 'rspec'            # test framework
  gem 'rspec-mocks'      # more test bits

  gem 'guard'
  gem 'rb-fsevent'       # necessary for guard to watch the fs
  gem 'guard-rspec'      # teach guard to monitor your changes and run test aswhen

                         # 
                         # $ guard init rspec  # will build a default Guardfile
                         #                     

end


# server bits
gem 'rack'
gem "sinatra"
gem "sinatra-contrib"

# assets (javascript, stylesheets)
gem 'sprockets'
gem 'sass'
gem 'coffee-script'

